"""empty message

Revision ID: 0cec69e6ab28
Revises: 0170cd68dab3
Create Date: 2020-12-25 15:06:41.711051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cec69e6ab28'
down_revision = '0170cd68dab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('clock_in_end', sa.Time(), nullable=True))
    op.add_column('schedules', sa.Column('clock_in_start', sa.Time(), nullable=True))
    op.add_column('schedules', sa.Column('clock_out_end', sa.Time(), nullable=True))
    op.add_column('schedules', sa.Column('clock_out_start', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'clock_out_start')
    op.drop_column('schedules', 'clock_out_end')
    op.drop_column('schedules', 'clock_in_start')
    op.drop_column('schedules', 'clock_in_end')
    # ### end Alembic commands ###
