"""empty message

Revision ID: adad5ecaab00
Revises: 2b0ad2557b7e
Create Date: 2020-12-26 15:29:09.433895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adad5ecaab00'
down_revision = '2b0ad2557b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('allowed_early_leave', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('allowed_late_arrival', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'allowed_late_arrival')
    op.drop_column('schedules', 'allowed_early_leave')
    # ### end Alembic commands ###
