"""empty message

Revision ID: d62575c3373f
Revises: 0cec69e6ab28
Create Date: 2020-12-25 15:11:34.410875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd62575c3373f'
down_revision = '0cec69e6ab28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'clock_out_start')
    op.drop_column('schedules', 'clock_out_end')
    op.drop_column('schedules', 'clock_in_start')
    op.drop_column('schedules', 'clock_in_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('clock_in_end', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('clock_in_start', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('clock_out_end', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('clock_out_start', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
